services:
  - type: web
    name: moviebox-backend
    env: python
    plan: free
    rootDir: .
    buildCommand: pip install -r render-backend/requirements.txt
    startCommand: bash -lc "python render-backend/write_token.py && gunicorn webapp.app:app --preload --workers 2 --threads 4 --timeout 120"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: AUTH_TOKEN
        sync: false
      # Optional alternative key name
      - key: TOKEN
        sync: false
